# Simulation

In this lesson, we will work through several examples of using random numbers to simulate real-world scenarios.

In [53]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(1349)

ModuleNotFoundError: No module named 'viz'

### How will we utilize Python to obtain probabilities?

We will utilize Monte Carlo simulations.

A Monte Carlo simulation is a means to recreate potential events and empirically take the results of simiulated trials to obtain a reasonably precise estimate of a desired probability.

What does this mean for us here?

In [ ]:
# Let's take a hypothetical base probability. 
# What is the probability of rolling a one (1) on a single, standard, fair six-sided die?


In [ ]:
# Potential outcomes of a die roll:


In [ ]:
# options that equal 1: just 1, literally one

In [ ]:
# Now how would we do this with a simulation?


In [ ]:
# We will do it utilizing a large number of trials, that we calculate.

In [ ]:
# Allow us to examine the same problem: Probability of rolling a 1 on a fair six-sided die.

In [ ]:
# First, we will set a value for the number of trials that we want to conduct.
# We have the power of computation at our finger tips, so let's shoot for something like one million.



In [ ]:
# We have one die roll for each trial, which is our event, that we call a single simulation


In [ ]:
# We will do a single simulation one million times, with each simulation being a die roll.

In [ ]:
# let's make our simulations!

## Generating Random Numbers with Numpy

The `numpy.random` module provides a number of functions for generating random numbers.

- `np.random.choice`: selects random options from a list
- `np.random.uniform`: generates numbers between a given lower and upper bound
- `np.random.random`: generates numbers between 0 and 1
- `np.random.randn`: generates numbers from the standard normal distribution
- `np.random.normal`: generates numbers from a normal distribution with a specified mean and standard deviation

## Example Problems

### Carnival Dice Rolls

> You are at a carnival and come across a person in a booth offering you a game
> of "chance" (as people in booths at carnivals tend to do).

> You pay 5 dollars and roll 3 dice. If the sum of the dice rolls is greater
> than 12, you get 15 dollars. If it's less than or equal to 12, you get
> nothing.

> Assuming the dice are fair, should you play this game? How would this change
> if the winning condition was a sum greater than *or equal to* 12?

To simulate this problem, we'll write the python code to simulate the scenario described above, then repeat it a large amount of times.

One way we can keep track of all the simulations is to use a 2-dimensional matrix. We can create a matrix where each row represents one "trial". Each row will have 3 columns, representing the 3 dice rolls.

In [ ]:
n_trials = 
n_dice = 

rolls = 

Here we used the `choice` function to randomly select an element out of the list of the number 1-6, effectively simulating a dice roll. The second argument supplied to `choice` is the total number of dice to roll. Once we have generated all the dice rolls, we use the `.reshape` method to create our matrix with 3 columns and 10,000 rows.

Now that we have all of the simulated dice rolls, we want to get the sum of the dice rolls for each trial. To do this, we can use the `.sum` function and specify that we want the sum of every row (as opposed to the sum of all the numbers, or the sum by column) with the `axis` key word argument.

In [ ]:
sums_by_trial = 
sums_by_trial

Let's pause here for a minute and visualize the data we have:

In [ ]:
viz.simulation_example1(sums_by_trial)

The area shaded in lightblue represents our chance of winning, that is, the number of times that the sum of 3 dice rolls is greater than 12.

We can now convert each value in our array to a boolean value indicating whether or not we won:

To calculate an overall win rate, we can treat each win as a `1` and each loss as `0`, then take the average of the array:

Now that we know our win rate, we can calculate the expected profit:

In [ ]:
expected_winnings = 
cost = 
expected_profit = 
expected_profit

So we would expect, based on our simulations, on average, to lose a little over a dollar everytime we play this game.

To answer the last part of the question, we can recalculate our win rate based on the sums being greater than or equal to 12:

In [ ]:
wins = 
win_rate = 
expected_winnings = 
cost = 
expected_profit = 
expected_profit

If our win condition changes to the sum being greater than or equal to 12, then, based on our simulations, on average, we expect to win about 58 cents.

## Mini Exercise:

What is the probability of rolling "snake eyes" on a roll of two (fair) dice?

In [1]:
(1/6) * (1/6)

0.027777777777777776

### No Rest or Relaxation

> There's a 30% chance my son takes a nap on any given weekend day. What is the chance that he takes a nap at least one day this weekend? What is the probability that he doesn't nap at all?

Let's first do a little bit of setup:

In [ ]:
p_nap = 
ndays = n_cols = 
n_simulated_weekends = 

To simulate the results from many weekends, we'll create a 2 x 10,000 matrix, with 2 being the number of days in a weekend and 10,000 being the number of simulations we want to run.

To determine whether or not a nap is taken on a given day, we'll generate a random number between 0 and 1, and say that it is a nap if it is less than our probability of taking a nap.

Now that we have each day as either true or false, we can take the sum of each row to find the total number of naps for the weekend. When we sum an array of boolean values, numpy will treat `True` as 1 and `False` as 0.

Now we have the results of our simulation, an array where each number in the array represents how many naps were taken in a two day weekend.

In [ ]:
viz.simulation_example2(naps)

We can use this to answer our original questions, what is the probability that at least one nap is taken?

What is the probability no naps are taken?

## Mini Exercise:

There are ten options in a blind-box style collectable, but you are only likely to get the one you want the most at a probability of one out of every twenty boxes because its a little rarer.

What is the probability of getting your desired collectable if you buy three blindbox toys?

### One With Dataframes

Let's take a look at one more problem:

> What is the probability of getting at least one 3 in 3 dice rolls?

To simulate this, we'll use a similar strategy to how we modeled the dice rolls in the previous example, but this time, we'll store the results in a pandas dataframe so that we can apply a lambda function that will check to see if one of the rolls was a 3.

In [ ]:
n_simulations = nrows = 
n_dice_rolled = ncols = 

rolls = 

Let's break down what's going on here:

1. First we assign values for the number of rows and columns we are going to use
1. Next we create the `rolls` variable that holds a 3 x 10,000 matrix where each element is a randomly chosen number from 1 to 6
1. Lastly we create a dataframe from the rolls
    1. `pd.DataFrame(rolls)` converts our 2d numpy matrix to a pandas DataFrame
    1. `.apply(...` applies a function to each **row** in our dataframe, because we specified `axis=1`, the function will be called with each row as it's argument. The body of the function checks to see if the value `3` is in the values of the row, and will return either `True` or `False`
    1. `.mean()` takes our resulting series of boolean values, and treats `True` as 1 and `False` as 0, to give us the average rate of `True`s, in this case, the simulated probability of getting a 3 in 3 dice rolls.

## Mini Exercise:

Recreate the blindbox problem utilizing the above strategy!


## Exercises

Within your `codeup-data-science directory`, create a directory named `statistics-exercises`. This will be where you do your work for this module. Create a repository on GitHub with the same name, and link your local repository to GitHub.

Do your work for this exercise in either a python file named `simulation.py` or a jupyter notebook named `simulation.ipynb`.

1. How likely is it that you roll doubles when rolling two dice?

1. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

1. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

1. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

1. Compare Heights

    - Men have an average height of 178 cm and standard deviation of 8cm.
    - Women have a mean of 170, sd = 6cm.
    - If a man and woman are chosen at random, P(woman taller than man)?

1. When installing anaconda on a student's computer, there's a 1 in 250 chance
   that the download is corrupted and the installation fails. What are the odds
   that after having 50 students download anaconda, no one has an installation
   issue?  100 students?

    What is the probability that we observe an installation issue within the first
    150 students that download anaconda?

    How likely is it that 450 students all download anaconda without an issue?

1. There's a 70% chance on any given day that there will be at least one food
   truck at Travis Park. However, you haven't seen a food truck there in 3 days.
   How unlikely is this?

    How likely is it that a food truck will show up sometime this week?

1. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

#### Bonus Exercises
- [Mage Duel](https://gist.github.com/ryanorsinger/2996446f02c1bf30fcb3f8fdb88bd51d)
- [Chuck a Luck](https://gist.github.com/ryanorsinger/eac1d7b7e978f90b8390bdc056312123)

# Exercises

1. How likely is it that you roll doubles when rolling two dice?

In [2]:
outcomes = [1,2,3,4,5,6]
n_rows = 1_000_000
n_cols = 2

In [3]:
rolls = np.random.choice(outcomes, size=(n_rows, n_cols))

In [4]:
rolls[:5] # to view outcomes

array([[2, 1],
       [2, 5],
       [2, 4],
       [2, 4],
       [3, 3]])

In [5]:
rolls.shape # to view rows and cols

(1000000, 2)

In [7]:
# using madeline's list comprehension
dubs = [len(np.unique(rolls[n])) for n in range(0, n_rows-1) if len(np.unique(rolls[n])) ==1]
len(dubs)

166759

In [8]:
calculated_prob = len(dubs) / len(rolls)
calculated_prob

0.166759

In [9]:
print(f'The probability that we will flip at least 3 heads over {n_cols} coins is {calculated_prob}')

The probability that we will flip at least 3 heads over 2 coins is 0.166759


2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [11]:
n_rows = 1_000_000
n_cols = 8
heads = 1
tails = 0
flips = np.random.choice([heads, tails], size=(n_rows, n_cols))

In [12]:
flips

array([[1, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [1, 1, 1, ..., 0, 0, 1]])

In [13]:
numheads = flips.sum(axis=1)

In [14]:
calculated_prob = (numheads == 3).mean()
print(f'The probability that we will flip exactly 3 heads over {n_cols} coins is {calculated_prob}')

The probability that we will flip exactly 3 heads over 8 coins is 0.218619


In [15]:
calculated_prob = (numheads >= 3).mean()
print(f'The probability that we will flip at least 3 heads over {n_cols} coins is {calculated_prob}')

The probability that we will flip at least 3 heads over 8 coins is 0.856031


3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [16]:
n_rows = 1_000_000
n_cols = 2
prob_ds = 0.25
data = np.random.random((n_rows, n_cols))

In [17]:
((data < prob_ds).sum(axis=1) == 2).mean()

0.062448

4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [18]:
pop_avg = 3
pop_std = 1.5
n_cols = 5
n_rows = 1_000_000
simulated_consumed_potars = np.random.normal(pop_avg, pop_std, size=(n_rows, n_cols))
simulated_consumed_potars

array([[ 3.90043116,  3.13912778,  2.57172143,  3.76952808,  1.91720663],
       [ 3.6549657 ,  4.14136071,  2.33072873,  2.39837942, -0.64483556],
       [ 3.68183453,  3.59482662,  3.75834109,  1.81592552,  2.10712251],
       ...,
       [ 3.85982974,  5.00770573, -0.49496043,  1.67278349,  4.10496555],
       [ 0.35609451,  2.26431049,  6.39543383,  3.18320633,  4.34033877],
       [ 1.91684987,  4.1586816 ,  1.49944651,  1.36678324,  3.04004163]])

In [19]:
simulated_consumed_potars.sum(axis=1)

array([15.29801507, 11.88059901, 14.95805027, ..., 14.15032408,
       16.53938392, 11.98180283])

In [20]:
calculated_prob = (simulated_consumed_potars.sum(axis=1) <= 16).mean()
print(f'The probability that there will still be poptarts in the vending machine after {n_cols} days is {calculated_prob}')

The probability that there will still be poptarts in the vending machine after 5 days is 0.617243


5. Compare Heights
 - Men have an average height of 178 cm and standard deviation of 8cm.
 - Women have a mean of 170, sd = 6cm.
 - If a man and woman are chosen at random, P(woman taller than man)?

In [21]:
men_avg = 178
men_std = 8
wmn_avg = 170
wmn_std = 6
s_men = np.random.normal(men_avg, men_std, 1_000_000)
s_men[:5]

array([176.63762966, 183.01834803, 193.14459322, 162.75323531,
       181.13381144])

In [22]:
s_wmn = np.random.normal(wmn_avg, wmn_std, 1_000_000)

In [24]:
calculated_prob = (s_wmn > s_men).mean()
print(f'The probability that we will have a woman taller than a man presuming a normal distribution is {calculated_prob}')

The probability that we will have a woman taller than a man presuming a normal distribution is 0.211636


6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
 - What is the probability that we observe an installation issue within the first 150 students that download anaconda?
 - How likely is it that 450 students all download anaconda without an issue?

In [25]:
nrows = 1_000_000
n_cols = 50
conda_failure = 1
great_success = 0
prob_failure = (1/250)
prob_failure

0.004

In [26]:
installs = np.random.random((nrows, n_cols))
((installs < prob_failure).sum(axis=1) == 0).mean()

0.81893

In [28]:
n_cols = 100
conda_failure = 1
great_success = 0
prob_failure = (1/250)
prob_failure

0.004

In [29]:
installs = np.random.random((nrows, n_cols))
((installs < prob_failure).sum(axis=1) == 0).mean()

0.67018

In [30]:
n_cols = 450
conda_failure = 1
great_success = 0
prob_failure = (1/250)
prob_failure

0.004

In [34]:
installs = np.random.random((nrows, n_cols))
((installs < prob_failure).sum(axis=1) == 0).mean()

0.165375

In [35]:
n_cols = 150
conda_failure = 1
great_success = 0
prob_failure = (1/250)
prob_failure

0.004

In [36]:
installs = np.random.random((nrows, n_cols))
((installs < prob_failure).sum(axis=1) > 0).mean()

0.452184

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?
 - How likely is it that a food truck will show up sometime this week?

In [37]:
n_rows = 1_000_000
n_cols = 3
food_truck = 1
no_truck = 0
truck_prob = 0.7
data = np.random.random((n_rows, n_cols))
((data < truck_prob).sum(axis=1) == 0).mean()

0.026942

In [38]:
calculated_prob = ((data < truck_prob).sum(axis=1) == 0).mean()
print(f'The probability that we will not have seen a food truck over the course of {n_cols} days is {calculated_prob}')

The probability that we will not have seen a food truck over the course of 3 days is 0.026942


In [ ]:
n_rows = 1_000_000
n_cols = 2
food_truck = 1
no_truck = 0
truck_prob = 0.7

In [ ]:
lunch_days = np.random.random((n_rows, n_cols))
calculated_prob = ((lunch_days < truck_prob).sum(axis=1) > 0).mean()

In [39]:
print(f'The probability that we have seen a food truck over the course of {n_cols} days is {calculated_prob}')

The probability that we have seen a food truck over the course of 3 days is 0.026942


8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [41]:
outcomes = range(0, 365)
n_trials = 23
n_simulations = 1_000_000
classrooms = np.random.choice(outcomes, size=(n_simulations, n_trials))

In [42]:
list_of_twin_bdays = [len(np.unique(classrooms[n])) for n in range(0, n_simulations-1) if len(np.unique(classrooms[n])) < 23]

In [43]:
prop_twinsies = len(list_of_twin_bdays) / n_simulations
print(f'The probability that we will have one or more shared birthdays over {n_trials} students is {prop_twinsies}')

The probability that we will have one or more shared birthdays over 23 students is 0.506909


In [47]:
outcomes = range(0, 365)
n_trials = 20
n_simulations = 1_000_000
classrooms = np.random.choice(outcomes, size=(n_simulations, n_trials))

In [48]:
list_of_twin_bdays = [len(np.unique(classrooms[n])) for n in range(0, n_simulations-1) if len(np.unique(classrooms[n])) < 20]

In [49]:
prop_twinsies = len(list_of_twin_bdays) / n_simulations
print(f'The probability that we will have one or more shared birthdays over {n_trials} students is {prop_twinsies}')

The probability that we will have one or more shared birthdays over 20 students is 0.411054


In [50]:
outcomes = range(0, 365)
n_trials = 40
n_simulations = 1_000_000
classrooms = np.random.choice(outcomes, size=(n_simulations, n_trials))

In [51]:
list_of_twin_bdays = [len(np.unique(classrooms[n])) for n in range(0, n_simulations-1) if len(np.unique(classrooms[n])) < 40]

In [52]:
prop_twinsies = len(list_of_twin_bdays) / n_simulations
print(f'The probability that we will have one or more shared birthdays over {n_trials} students is {prop_twinsies}')

The probability that we will have one or more shared birthdays over 40 students is 0.8909
